### ISSUE TITLE
[feature] 회원 설정 업데이트 API

### ISSUE THREAD

**Issue by ghost** [Wanted-Internship-Team-Careerly/Location-Based-Foodie-Service#18]
## 📌 Feature Issue

* 회원의 위치인 위도, 경도를 업데이트 합니다.
* 점심 추천 기능 사용 여부를 업데이트 합니다.

## To-do

- [x] 회원 위도, 경도, 점심 추천 기능 사용 업데이트 API 작성
- [x] 서비스 레이어 테스트 코드 작성
- [x] 포스트맨 실행 결과 출력 

## ETC

<img width="944" alt="스크린샷 2023-11-04 오전 1 28 13" src="https://github.com/Wanted-Internship-Team-Careerly/Location-Based-Foodie-Service/assets/46531692/b52b692b-9427-4cd4-8718-9b01887a177e">
